version: "3.7"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - "db:/var/lib/postgresql/data"

  zars-keycloak:
    image: jboss/keycloak:16.1.1
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_IMPORT: /tmp/initial-realm.json
    volumes:
      - ${KEYCLOAKIMPORTFILE:-./init/initial-realm-prod.json}:/tmp/initial-realm.json
    depends_on:
      - db

volumes:
  db:
